title: "My Awesome Site"
description: "[A short description of your site's purpose]"

# Set default front matter values
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
